#!/usr/bin/perl
use Text::Levenshtein::Damerau;
# Defaults to using Pure Perl Text::Levenshtein::Damerau::PP, but has an XS addon Text::Levenshtein::Damerau::XS for massive speed imrovements.
# use Text::Levenshtein::Damerau::XS qw/xs_edistance/;
use utf8;

my (@word_list, @paronyms);

my $file = shift;
die "Usage: $0 LIST" unless $file;
open(LIST, "<:encoding(UTF-8)", $file)  or die "$0: Can't open $file $!";
push(@word_list, $_) while <LIST>;   # Read whole list

# Process whole list
foreach my $word (@word_list) {
  my $tld = Text::Levenshtein::Damerau->new($word);
  my $d_ref = $tld->dld({ list => \@word_list, max_distance => 2 });
  while( my ($k, $v) = each %$d_ref ) {
    # print "$k";
    push(@paronyms, $k);
  }
  # print "\n";
  push(@paronyms, "\n");
}
    open(my $out, ">:encoding(UTF-8)", $file . ".paronyms")
||  die "can't open UTF-8 encoded filename: $!";
print $out @paronyms;
close($out);
